//! `chops-search init` — scaffold a site's integration.
//!
//! The gap between "installed the binary" and "search works" was five
//! manual steps: write a config, create a page with the right element
//! ids, add gitignore lines, link two assets, and know that the runtime
//! lands in `out`. Every one of those is a place to get it subtly wrong
//! and see an empty results list with no error.
//!
//! What this does NOT do is edit templates. Where a search box belongs is
//! theme-specific — tabi wants `templates/tabi/extend_head.html`, another
//! theme wants `base.html`, a bare site wants neither — and a tool that
//! rewrites someone's layout on their behalf is a tool people stop
//! trusting. It prints the line and lets you place it.
//!
//! Nothing is ever overwritten. Re-running after editing the scaffold is
//! safe and reports what it skipped.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

const CONFIG: &str = r#"# chops-search — https://github.com/gitbadger-clan/chops-search
#
# Paths resolve relative to THIS file, so `chops-search build` works from
# anywhere inside the site.

content = "content"
out     = "static/search"
model   = ".chops-search/model"

# PCA target. The model's native size is 256; 128 halves the eager prefix
# and every per-query range fetch. Re-run `chops-search eval` after
# changing it — dimensionality reduction is real information loss.
dims = 128

# Term-frequency weights. Tags are the author's own statement of what a
# page is about, so they outweigh the title, which outweighs body text.
# title_weight = 2
# tag_weight   = 4

# chunk_chars = 600
# prefix_rows = 2048
"#;

const SEARCH_PAGE: &str = r#"+++
title = "Search"
# Zola silently drops pages with no sort key from a sorted section, so a
# search page without one renders nowhere and 404s. Both keys are here
# because a section may sort by either, and neither value is meaningful
# for a page that is not content.
date = 1970-01-01
weight = 999
# The search page has nothing to find; indexing it makes it a result for
# every query typed into it.
in_search_index = false
+++

<div class="chops">
  <div class="chops-bar">
    <span class="chops-icon"></span>
    <input id="chops-input" type="search" placeholder="Search…"
           autocomplete="off" spellcheck="false"
           role="combobox" aria-expanded="false" aria-controls="chops-results"
           aria-autocomplete="list">
    <button type="button" class="chops-clear" data-chops-clear></button>
  </div>
  <span id="chops-mode" class="chops-mode" aria-live="polite"></span>
  <ul id="chops-results" class="chops-results" role="listbox"></ul>
</div>

<link rel="stylesheet" href="/search/chops-search.css">
<script defer src="/search/chops-search.js"></script>
"#;

const GITIGNORE_LINES: &[(&str, &str)] = &[
    ("/static/search/", "generated by `chops-search build`"),
    (
        "/.chops-search/model/",
        "~30 MB; the lockfile beside it is what to commit",
    ),
];

/// Scaffold into `root`. `with_page` controls whether a dedicated search
/// page is created — sites using only the site-wide overlay don't need
/// one.
pub fn init(root: &Path, with_page: bool) -> Result<()> {
    let mut created = Vec::new();
    let mut skipped = Vec::new();

    write_new(
        &root.join("chops-search.toml"),
        CONFIG,
        &mut created,
        &mut skipped,
    )?;

    if with_page {
        let content = root.join("content");
        if content.is_dir() {
            write_new(
                &content.join("search.md"),
                SEARCH_PAGE,
                &mut created,
                &mut skipped,
            )?;
        } else {
            skipped.push(format!(
                "content/search.md (no content/ directory — is {} a Zola site?)",
                root.display()
            ));
        }
    }

    // Appended rather than written: a site's .gitignore is not ours to
    // replace, and duplicate entries are noise in every future diff.
    let gitignore = root.join(".gitignore");
    let existing = fs::read_to_string(&gitignore).unwrap_or_default();
    // Compare the pattern only. A previously written line may carry a
    // trailing comment, so a whole-line match would never fire and every
    // run would append again.
    let existing_patterns: Vec<&str> = existing
        .lines()
        .map(|l| l.split('#').next().unwrap_or("").trim())
        .filter(|p| !p.is_empty())
        .collect();
    let missing: Vec<&(&str, &str)> = GITIGNORE_LINES
        .iter()
        .filter(|(line, _)| !existing_patterns.contains(line))
        .collect();
    if missing.is_empty() {
        skipped.push(".gitignore (already covered)".to_string());
    } else {
        let mut out = existing;
        if !out.is_empty() && !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str("\n# chops-search\n");
        for (line, why) in &missing {
            out.push_str(&format!("# {why}\n{line}\n"));
        }
        fs::write(&gitignore, out).with_context(|| format!("writing {}", gitignore.display()))?;
        created.push(format!(".gitignore (+{} lines)", missing.len()));
    }

    for c in &created {
        println!("  created  {c}");
    }
    for s in &skipped {
        println!("  exists   {s}");
    }

    println!(
        r#"
Next:

  1. chops-search model fetch      download the embedding model (~30 MB, once)
  2. chops-search build            artifacts + runtime -> static/search/
  3. zola serve                    then visit /search/

For a search box on EVERY page, add this to your base template
(tabi: templates/tabi/extend_head.html). The script mounts its own overlay
on pages with no #chops-input, opened with Ctrl/Cmd-K or /:

  <link rel="stylesheet" href="{{{{ get_url(path='search/chops-search.css') }}}}">
  <script defer src="{{{{ get_url(path='search/chops-search.js') }}}}"></script>

Also set `build_search_index = false` in config.toml. Zola's own index is
dead weight alongside this one.
"#
    );
    Ok(())
}

fn write_new(
    path: &Path,
    body: &str,
    created: &mut Vec<String>,
    skipped: &mut Vec<String>,
) -> Result<()> {
    let name = path
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    if path.exists() {
        skipped.push(name);
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, body).with_context(|| format!("writing {}", path.display()))?;
    created.push(name);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp(name: &str) -> std::path::PathBuf {
        let p = std::env::temp_dir().join(format!("chops-init-{name}-{}", std::process::id()));
        fs::create_dir_all(p.join("content")).unwrap();
        p
    }

    #[test]
    fn creates_config_and_page() {
        let root = tmp("create");
        init(&root, true).unwrap();
        assert!(root.join("chops-search.toml").is_file());
        assert!(root.join("content/search.md").is_file());
        assert!(
            fs::read_to_string(root.join(".gitignore"))
                .unwrap()
                .contains("/static/search/")
        );
        fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn never_overwrites() {
        let root = tmp("idempotent");
        fs::write(root.join("chops-search.toml"), "content = \"mine\"\n").unwrap();
        init(&root, true).unwrap();
        assert_eq!(
            fs::read_to_string(root.join("chops-search.toml")).unwrap(),
            "content = \"mine\"\n",
            "an existing config must survive"
        );
        fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn gitignore_lines_are_not_duplicated() {
        let root = tmp("gitignore");
        init(&root, false).unwrap();
        init(&root, false).unwrap();
        let text = fs::read_to_string(root.join(".gitignore")).unwrap();
        assert_eq!(text.matches("/static/search/").count(), 1);
        fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn existing_gitignore_is_preserved() {
        let root = tmp("append");
        fs::write(root.join(".gitignore"), "/public/\n/target/\n").unwrap();
        init(&root, false).unwrap();
        let text = fs::read_to_string(root.join(".gitignore")).unwrap();
        assert!(text.contains("/public/"));
        assert!(text.contains("/target/"));
        assert!(text.contains("/static/search/"));
        fs::remove_dir_all(&root).ok();
    }
}
